services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - redis
      - qdrant

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
